# SPDX-FileCopyrightText: 2023 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

# Page settings...
title: Main Page
description: Entry point to my little website

# Theme settings...
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
