# SPDX-FileCopyrightText: 2023 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

# Page settings...
title: Awklesses' Little Website
description: Wanna see some cool stuff?

# Theme settings...
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
